version: '3.8'

services:
  rag-app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./artifacts:/app/artifacts
    restart: unless-stopped