version: '3.8'

services:
  rag-app:
    build: .
    expose:
      - "8501"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./artifacts:/app/artifacts
    restart: unless-stopped
    networks:
      - rag-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rag-app
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge